/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oop.waterbill;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author student
 */
public class InputPanel extends javax.swing.JPanel {

    /**
     * Creates new form InputPanel
     */
    
     GridBagLayout layout = new GridBagLayout();
     GridBagConstraints c = new GridBagConstraints();
    SingleInternal single;
    SingleInternal multiple;
    ImportInternal bulk;
    public InputPanel() {
        initComponents();
        single = new SingleInternal(true);
        multiple = new SingleInternal(false);
        bulk = new ImportInternal();
         DynaPanel.setLayout(layout);
       
        c.gridx = 0;
       c.gridy = 0;
       DynaPanel.add(single,c);
       DynaPanel.add(multiple,c);
       DynaPanel.add(bulk,c);
       //DynaPanel.add(input,c);
        //payment.setVisible(true);
        //records.setVisible(false);

        resetColor(1);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bulkbutton = new javax.swing.JButton();
        importbutton = new javax.swing.JButton();
        singlebutton = new javax.swing.JButton();
        DynaPanel = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(134, 207, 190));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(253, 253, 253));
        jLabel1.setText("Water Readings");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(253, 253, 253));
        jLabel2.setText("Input Section");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        bulkbutton.setBackground(new java.awt.Color(134, 207, 190));
        bulkbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bulkbutton.setForeground(new java.awt.Color(253, 253, 253));
        bulkbutton.setText("Bulk Input");
        bulkbutton.setContentAreaFilled(false);
        bulkbutton.setOpaque(true);
        bulkbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulkbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(bulkbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, -1, 50));

        importbutton.setBackground(new java.awt.Color(134, 207, 190));
        importbutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        importbutton.setForeground(new java.awt.Color(253, 253, 253));
        importbutton.setText("Import File");
        importbutton.setContentAreaFilled(false);
        importbutton.setOpaque(true);
        importbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importbuttonActionPerformed(evt);
            }
        });
        jPanel2.add(importbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, 50));

        singlebutton.setBackground(new java.awt.Color(134, 207, 190));
        singlebutton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        singlebutton.setForeground(new java.awt.Color(253, 253, 253));
        singlebutton.setText("Single Input");
        singlebutton.setContentAreaFilled(false);
        singlebutton.setOpaque(true);
        singlebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlebuttonActionPerformed(evt);
            }
        });
        jPanel2.add(singlebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 680, 80));

        javax.swing.GroupLayout DynaPanelLayout = new javax.swing.GroupLayout(DynaPanel);
        DynaPanel.setLayout(DynaPanelLayout);
        DynaPanelLayout.setHorizontalGroup(
            DynaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );
        DynaPanelLayout.setVerticalGroup(
            DynaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 370, Short.MAX_VALUE)
        );

        jPanel1.add(DynaPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 670, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void singlebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singlebuttonActionPerformed
        // TODO add your handling code here:
        resetColor(1);
        
    }//GEN-LAST:event_singlebuttonActionPerformed

    private void bulkbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulkbuttonActionPerformed
        // TODO add your handling code here:
        resetColor(2);
    }//GEN-LAST:event_bulkbuttonActionPerformed

    private void importbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importbuttonActionPerformed
        // TODO add your handling code here:
        resetColor(3);
    }//GEN-LAST:event_importbuttonActionPerformed

private void resetColor(int choice){
Color white = new Color(253, 253, 253);
Color green = new Color(134, 207, 190);

 switch(choice){
            case 1:
                singlebutton.setBackground(white);
                bulkbutton.setBackground(green);
                importbutton.setBackground(green);
                singlebutton.setForeground(green);
                bulkbutton.setForeground(white);
                importbutton.setForeground(white);
                single.setVisible(true);
                multiple.setVisible(false);
                bulk.setVisible(false);
                break;
            case 2:
                 singlebutton.setBackground(green);
                bulkbutton.setBackground(white);
                importbutton.setBackground(green);
                singlebutton.setForeground(white);
                bulkbutton.setForeground(green);
                importbutton.setForeground(white);
                 single.setVisible(false);
                bulk.setVisible(false);
                 multiple.setVisible(true);
        break;
            case 3:
               singlebutton.setBackground(green);
                bulkbutton.setBackground(green);
                importbutton.setBackground(white);
                singlebutton.setForeground(white);
                bulkbutton.setForeground(white);
                importbutton.setForeground(green);
                single.setVisible(false);
                bulk.setVisible(true);
                 multiple.setVisible(false);
                break;
            default:
                break;
        
        
        
        }


}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynaPanel;
    private javax.swing.JButton bulkbutton;
    private javax.swing.JButton importbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton singlebutton;
    // End of variables declaration//GEN-END:variables
}
