/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oop.waterbill;

/**
 *
 * @author User
 */
public class PaymentPanel extends javax.swing.JPanel {

    /**
     * Creates new form PaymentPanel
     */
    public PaymentPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        accountpayment = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        genderpayment = new javax.swing.JTextField();
        homepayment = new javax.swing.JTextField();
        firstpayment = new javax.swing.JTextField();
        middlepayment = new javax.swing.JTextField();
        previouspayment = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lastpayment = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        areapaymentcombo = new java.awt.Choice();
        jLabel11 = new javax.swing.JLabel();
        connectionpaymentcombo = new java.awt.Choice();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        agepayment = new javax.swing.JTextField();
        coordpaymentcombo = new java.awt.Choice();
        jLabel14 = new javax.swing.JLabel();
        currentpayment = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        amountpayment = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        changepayment = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        meternopayment = new javax.swing.JTextField();
        clearbuttonpayment = new javax.swing.JButton();
        confirmbuttonpayment = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(131, 95, 193));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Account Number: ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 280, -1));

        accountpayment.setBackground(new java.awt.Color(131, 95, 193));
        accountpayment.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        accountpayment.setForeground(new java.awt.Color(186, 186, 188));
        accountpayment.setText("Enter Account Number");
        accountpayment.setBorder(null);
        accountpayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountpaymentMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountpaymentMousePressed(evt);
            }
        });
        jPanel2.add(accountpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 270, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payments Section");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(253, 253, 253));
        jButton1.setForeground(new java.awt.Color(131, 95, 193));
        jButton1.setText("Enter");
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(true);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 690, 90));

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Gender");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Middle Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Last Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Home Address");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Age");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        genderpayment.setBackground(new java.awt.Color(253, 253, 253));
        genderpayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(genderpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 40, -1));

        homepayment.setBackground(new java.awt.Color(253, 253, 253));
        homepayment.setForeground(new java.awt.Color(51, 51, 51));
        homepayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepaymentActionPerformed(evt);
            }
        });
        jPanel1.add(homepayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 430, -1));

        firstpayment.setBackground(new java.awt.Color(253, 253, 253));
        firstpayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(firstpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 140, -1));

        middlepayment.setBackground(new java.awt.Color(253, 253, 253));
        middlepayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(middlepayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 130, -1));

        previouspayment.setBackground(new java.awt.Color(253, 253, 253));
        previouspayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(previouspayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 140, -1));

        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("First Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        lastpayment.setBackground(new java.awt.Color(253, 253, 253));
        lastpayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(lastpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, -1));

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Area");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));
        jPanel1.add(areapaymentcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 244, 110, 24));

        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Coordinator");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        jPanel1.add(connectionpaymentcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 180, -1));

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Previous Bill");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 80, -1));

        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Type of Connection");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        agepayment.setBackground(new java.awt.Color(253, 253, 253));
        agepayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(agepayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 40, -1));
        jPanel1.add(coordpaymentcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 312, 145, -1));

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Meter No.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 80, -1));

        currentpayment.setBackground(new java.awt.Color(253, 253, 253));
        currentpayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(currentpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 140, -1));

        jPanel3.setBackground(new java.awt.Color(131, 95, 193));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Amount Paid");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        amountpayment.setBackground(new java.awt.Color(253, 253, 253));
        amountpayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(amountpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Change");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, 30));

        changepayment.setBackground(new java.awt.Color(253, 253, 253));
        changepayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(changepayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 100, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 310, 70));

        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Current Bill");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 80, -1));

        meternopayment.setBackground(new java.awt.Color(253, 253, 253));
        meternopayment.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.add(meternopayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 70, -1));

        clearbuttonpayment.setBackground(new java.awt.Color(131, 95, 193));
        clearbuttonpayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearbuttonpayment.setForeground(new java.awt.Color(255, 255, 255));
        clearbuttonpayment.setText("Clear");
        clearbuttonpayment.setContentAreaFilled(false);
        clearbuttonpayment.setOpaque(true);
        jPanel1.add(clearbuttonpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 100, 50));

        confirmbuttonpayment.setBackground(new java.awt.Color(131, 95, 193));
        confirmbuttonpayment.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmbuttonpayment.setForeground(new java.awt.Color(255, 255, 255));
        confirmbuttonpayment.setText("Cofirm");
        confirmbuttonpayment.setContentAreaFilled(false);
        confirmbuttonpayment.setOpaque(true);
        jPanel1.add(confirmbuttonpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 100, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void homepaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homepaymentActionPerformed

    private void accountpaymentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountpaymentMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_accountpaymentMouseExited

    private void accountpaymentMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountpaymentMousePressed
        // TODO add your handling code here:
        accountpayment.setText("");
    }//GEN-LAST:event_accountpaymentMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountpayment;
    private javax.swing.JTextField agepayment;
    private javax.swing.JTextField amountpayment;
    private java.awt.Choice areapaymentcombo;
    private javax.swing.JTextField changepayment;
    private javax.swing.JButton clearbuttonpayment;
    private javax.swing.JButton confirmbuttonpayment;
    private java.awt.Choice connectionpaymentcombo;
    private java.awt.Choice coordpaymentcombo;
    private javax.swing.JTextField currentpayment;
    private javax.swing.JTextField firstpayment;
    private javax.swing.JTextField genderpayment;
    private javax.swing.JTextField homepayment;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastpayment;
    private javax.swing.JTextField meternopayment;
    private javax.swing.JTextField middlepayment;
    private javax.swing.JTextField previouspayment;
    // End of variables declaration//GEN-END:variables
}
