/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.oop.waterbill;

/**
 *
 * @author User
 */
public class RecordsPanel extends javax.swing.JPanel {

    /**
     * Creates new form RecordsPanel
     */
    public RecordsPanel() {
        initComponents();
        
        categrecordcombo.add("Date");
        categrecordcombo.add("Bill");
        orderrecordcombo.add("Ascending");
        orderrecordcombo.add("Descending");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        recordtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        accountrecords = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        placeholder = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        searchrecord = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        categrecordcombo = new java.awt.Choice();
        jLabel5 = new javax.swing.JLabel();
        orderrecordcombo = new java.awt.Choice();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(253, 253, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        recordtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "REF. NO.", "DATE", "BILL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(recordtable);
        if (recordtable.getColumnModel().getColumnCount() > 0) {
            recordtable.getColumnModel().getColumn(0).setResizable(false);
            recordtable.getColumnModel().getColumn(1).setResizable(false);
            recordtable.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 610, 224));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Account Number:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        accountrecords.setBackground(new java.awt.Color(253, 253, 253));
        accountrecords.setForeground(new java.awt.Color(186, 186, 188));
        accountrecords.setText("Enter Account Number");
        accountrecords.setBorder(null);
        accountrecords.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                accountrecordsMousePressed(evt);
            }
        });
        jPanel1.add(accountrecords, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 231, 20));

        jPanel2.setBackground(new java.awt.Color(218, 99, 93));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 253, 253));
        jLabel2.setText("Billing History of ____________________________");
        jLabel2.setAlignmentY(0.0F);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        placeholder.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        placeholder.setForeground(new java.awt.Color(253, 253, 253));
        placeholder.setText("Marjay Tapay");
        jPanel2.add(placeholder, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(253, 253, 253));
        jLabel3.setText("Records Section");
        jLabel3.setAlignmentY(0.0F);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 680, 100));

        searchrecord.setBackground(new java.awt.Color(33, 63, 87));
        searchrecord.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        searchrecord.setForeground(new java.awt.Color(255, 255, 255));
        searchrecord.setText("Search");
        searchrecord.setContentAreaFilled(false);
        searchrecord.setOpaque(true);
        jPanel1.add(searchrecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 70, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 220, 10));

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Sort by:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));
        jPanel1.add(categrecordcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 140, -1));

        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("in");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 20, 20));
        jPanel1.add(orderrecordcombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 140, -1));

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("order");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void accountrecordsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountrecordsMousePressed
        // TODO add your handling code here:
        accountrecords.setText("");
    }//GEN-LAST:event_accountrecordsMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountrecords;
    private java.awt.Choice categrecordcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Choice orderrecordcombo;
    private javax.swing.JLabel placeholder;
    private javax.swing.JTable recordtable;
    private javax.swing.JButton searchrecord;
    // End of variables declaration//GEN-END:variables
}
